/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as UsersRouteImport } from './routes/users'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as EventsIdIndexRouteImport } from './routes/events.$id.index'
import { Route as EventsIdEditRouteImport } from './routes/events.$id.edit'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NewsRoute,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdIndexRoute = EventsIdIndexRouteImport.update({
  id: '/events/$id/',
  path: '/events/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdEditRoute = EventsIdEditRouteImport.update({
  id: '/events/$id/edit',
  path: '/events/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/availability': typeof AvailabilityRoute
  '/change-password': typeof ChangePasswordRoute
  '/leads': typeof LeadsRoute
  '/more': typeof MoreRoute
  '/news': typeof NewsRouteWithChildren
  '/pipeline': typeof PipelineRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/users': typeof UsersRoute
  '/whatsapp': typeof WhatsappRoute
  '/events/new': typeof EventsNewRoute
  '/news/$id': typeof NewsIdRoute
  '/p/$id': typeof PIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/events/': typeof EventsIndexRoute
  '/events/$id/edit': typeof EventsIdEditRoute
  '/events/$id/': typeof EventsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/availability': typeof AvailabilityRoute
  '/change-password': typeof ChangePasswordRoute
  '/leads': typeof LeadsRoute
  '/more': typeof MoreRoute
  '/news': typeof NewsRouteWithChildren
  '/pipeline': typeof PipelineRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/users': typeof UsersRoute
  '/whatsapp': typeof WhatsappRoute
  '/events/new': typeof EventsNewRoute
  '/news/$id': typeof NewsIdRoute
  '/p/$id': typeof PIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/events': typeof EventsIndexRoute
  '/events/$id/edit': typeof EventsIdEditRoute
  '/events/$id': typeof EventsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/availability': typeof AvailabilityRoute
  '/change-password': typeof ChangePasswordRoute
  '/leads': typeof LeadsRoute
  '/more': typeof MoreRoute
  '/news': typeof NewsRouteWithChildren
  '/pipeline': typeof PipelineRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/users': typeof UsersRoute
  '/whatsapp': typeof WhatsappRoute
  '/events/new': typeof EventsNewRoute
  '/news/$id': typeof NewsIdRoute
  '/p/$id': typeof PIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/events/': typeof EventsIndexRoute
  '/events/$id/edit': typeof EventsIdEditRoute
  '/events/$id/': typeof EventsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/analytics'
    | '/appointments'
    | '/auth'
    | '/availability'
    | '/change-password'
    | '/leads'
    | '/more'
    | '/news'
    | '/pipeline'
    | '/profile'
    | '/properties'
    | '/users'
    | '/whatsapp'
    | '/events/new'
    | '/news/$id'
    | '/p/$id'
    | '/properties/$id'
    | '/events/'
    | '/events/$id/edit'
    | '/events/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/analytics'
    | '/appointments'
    | '/auth'
    | '/availability'
    | '/change-password'
    | '/leads'
    | '/more'
    | '/news'
    | '/pipeline'
    | '/profile'
    | '/properties'
    | '/users'
    | '/whatsapp'
    | '/events/new'
    | '/news/$id'
    | '/p/$id'
    | '/properties/$id'
    | '/events'
    | '/events/$id/edit'
    | '/events/$id'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/analytics'
    | '/appointments'
    | '/auth'
    | '/availability'
    | '/change-password'
    | '/leads'
    | '/more'
    | '/news'
    | '/pipeline'
    | '/profile'
    | '/properties'
    | '/users'
    | '/whatsapp'
    | '/events/new'
    | '/news/$id'
    | '/p/$id'
    | '/properties/$id'
    | '/events/'
    | '/events/$id/edit'
    | '/events/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuthRoute: typeof AuthRoute
  AvailabilityRoute: typeof AvailabilityRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  LeadsRoute: typeof LeadsRoute
  MoreRoute: typeof MoreRoute
  NewsRoute: typeof NewsRouteWithChildren
  PipelineRoute: typeof PipelineRoute
  ProfileRoute: typeof ProfileRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  UsersRoute: typeof UsersRoute
  WhatsappRoute: typeof WhatsappRoute
  EventsNewRoute: typeof EventsNewRoute
  PIdRoute: typeof PIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  EventsIdEditRoute: typeof EventsIdEditRoute
  EventsIdIndexRoute: typeof EventsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/': {
      id: '/events/$id/'
      path: '/events/$id'
      fullPath: '/events/$id/'
      preLoaderRoute: typeof EventsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/edit': {
      id: '/events/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/events/$id/edit'
      preLoaderRoute: typeof EventsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NewsRouteChildren {
  NewsIdRoute: typeof NewsIdRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsIdRoute: NewsIdRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  AnalyticsRoute: AnalyticsRoute,
  AppointmentsRoute: AppointmentsRoute,
  AuthRoute: AuthRoute,
  AvailabilityRoute: AvailabilityRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  LeadsRoute: LeadsRoute,
  MoreRoute: MoreRoute,
  NewsRoute: NewsRouteWithChildren,
  PipelineRoute: PipelineRoute,
  ProfileRoute: ProfileRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  UsersRoute: UsersRoute,
  WhatsappRoute: WhatsappRoute,
  EventsNewRoute: EventsNewRoute,
  PIdRoute: PIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  EventsIdEditRoute: EventsIdEditRoute,
  EventsIdIndexRoute: EventsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
